name: Cypress BDD Scheduled Tests

on:
  workflow_dispatch:
  push:
    branches: [main, develop, typescript-migration]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 10 * * 1'
    - cron: '0 10 * * 1'

    - cron: '15 9 * * 2'
    - cron: '0 15 * * 2'
    - cron: '0 17 * * 2'
    - cron: '0 19 * * 2'
    - cron: '45 10 * * 3'
    - cron: '20 15 * * 3'
    - cron: '0 9 * * 4'
    - cron: '0 11 * * 4'
    - cron: '0 13 * * 4'

    - cron: '0 16 * * 4'

    - cron: '30 19 * * 4'
    - cron: '10 8 * * 5'
    - cron: '10 9 * * 5'
    - cron: '10 10 * * 5'
    - cron: '0 10 * * 6'
    - cron: '0 19 * * 6'
    - cron: '0 21 * * 6'


concurrency:
  group: cypress-tests
  cancel-in-progress: false

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # ← obligatoire pour git push
    strategy:
      fail-fast: false
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Lancer les tests Cypress (Cucumber BDD)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
        env:
          # ─── Configuration Cypress ────────────────────────────
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_APP_VERSION: v1

          # ─── Données utilisateur de test ──────────────────────
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_FULLNAME: ${{ secrets.TEST_USER_FULLNAME }}

          # ─── Credentials de connexion B2C ─────────────────────
          CYPRESS_USER_LOGIN: ${{ secrets.CYPRESS_USER_LOGIN }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}

      - name: Créer un commit de log
        if: always()
        run: |
          mkdir -p test-logs
          git config user.name "kitabrhi"
          git config user.email "kitabrhi.youssef.1@gmail.com"
          echo "Run #${{ github.run_number }} — $(date -u)" >> test-logs/run-history.log
          git add test-logs/run-history.log
          git commit -m "ci: scheduled test run #${{ github.run_number }}" || echo "Rien à committer"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload des rapports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-reports-${{ github.run_number }}
          path: |
            cypress/reports/
            cypress/screenshots/
            cypress/videos/
          retention-days: 7